### ISSUE TITLE
Have methods to modify other enchantment incompatibilities

### ISSUE THREAD

**Issue by MachineRat8** [PseudoResonance/InfinityMendingUnnerf#5]
Hello, I believe that a separate plugin or config in this plugin to allow modifying other enchantment incompatibilities (i.e. Protection, Fire Protection, Blast Protection, and Projectile Protection) would be useful, as there are no other plugins that are offering to do something like this, especially with this level of seamlessness regarding the integration into the game (no commands or extra GUIs). 
Thank you!

**Comment by PseudoResonance** [comment]
This seems a bit out of the scope of this plugin, but perhaps you could take a look at the code here to create another plugin to do that. It is fairly trivial, and I'd expect that even someone with very basic knowledge could copy and paste the code and hack together something that works.

However, the primary goal of this plugin was to fix what I, and many others believe to be a huge mistake on Mojang's part, not so much to change the game beyond what is acceptable in Vanilla Minecraft. Although I realize that infinity being missing on crossbows is another contentious topic, so perhaps it would make sense to add that as well. Both of these options are actually already available as configuration options in Purpur, a fork of Tuinity/Airplane/Paper/Spigot, and I added a check for Purpur in version 1.2.4 to simplify the process and hopefully reduce any future errors as long as the server is running Purpur.

**Comment by hyperdefined** [comment]
Protection enchants use the same exact method to check compatibility. If you change `EnchantmentInfiniteArrows` to `EnchantmentProtection`, it works. So in theory you could make another plugin that simply changes that class instead (literally could reuse all of the code) or add it to this plugin maybe as a configurable option.
