### ISSUE TITLE
Doesnt work with 1.18

### ISSUE THREAD

**Issue by NovusDevelops** [PseudoResonance/InfinityMendingUnnerf#8]
Doesn't work with 1.18

**Comment by hyperdefined** [comment]
This plugin works with 1.18, what is the problem?

**Comment by NovusDevelops** [comment]
I installed the plugin and restarted my server. When attempting to add mending to infinity it still doesn't work. Are there any required dependencies or permissions? The current version is 1.18.1 with papermc

**Comment by hyperdefined** [comment]
Look at your server's log, find anything that is labeled `InfinityMendingUnnerf`. Copy it and post it here. Or, you can also post your entire server log.

**Comment by PseudoResonance** [comment]
Sorry, I'm not sure why GitHub didn't notify me when this issue was opened... I'll take a look at it in a few hours.

**Comment by PseudoResonance** [comment]
I've tested the new version, 1.2.5, on Java 17 on a Minecraft 1.18 server and confirmed it is working. You can [download it here](https://github.com/PseudoResonance/InfinityMendingUnnerf/releases/tag/1.2.5).
